module.exports = Object.assign({},
    require('./Areas'),
    require('./Constants'),
    require('./Exponents'),
    require('./Geometry'),
    require('./Graphs'),
    require('./Other'),
    require('./Radicals'),
    require('./Trigonometry'),
    require('./Volume'),
    require('./Basic'),
    require('./Conversions'),
    require('./Logarithms'),
)